CREATE TABLE schgrcap.usuario (
	id bigserial NOT NULL,
	"name" varchar(100) NULL,
	balance numeric(15, 3) NULL,
	fecha_creacion timestamptz NULL,
	fecha_modificacion timestamptz NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE schgrcap.cashout (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	userid int8 NOT NULL,
	amount numeric(15, 3) NULL,
	fecha_creacion timestamptz NULL,
	fecha_modificacion timestamptz NULL,
	CONSTRAINT cashout_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cashout_idusuario FOREIGN KEY (userid) REFERENCES schgrcap.usuario(id)
);
